// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/blog': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog').default>>>>
    }
    '/api/googleReviews': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/googleReviews').default>>>>
    }
    '/api/projects': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects').default>>>>
    }
    '/api/search': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}