// Generated by nuxt-robots

declare module 'nitropack' {
  interface NitroApp {
    _robots: {
      ctx: import('../../node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext
      nuxtContentUrls?: Set<string>
    },
    _robotsRuleMactcher: (url: string) => string
  }
  interface NitroRouteRules {
    robots?: boolean | string | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRouteConfig {
    robots?: boolean | string | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRuntimeHooks {
    'robots:config': (ctx: import('../../node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext) => void | Promise<void>
    'robots:robots-txt': (ctx: import('../../node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsTxtContext) => void | Promise<void>
  }
}
declare module 'h3' {
  import type { RobotsContext } from '#robots/types'
  interface H3EventContext {
    robots: RobotsContext
  }
}

export {}
