
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BlocksContactShield': typeof import("../components/Blocks/ContactShield.vue")['default']
    'BlocksContactShield2': typeof import("../components/Blocks/ContactShield2.vue")['default']
    'BlocksContactShield3': typeof import("../components/Blocks/ContactShield3.vue")['default']
    'BlocksHomeStatsComponent': typeof import("../components/Blocks/HomeStatsComponent.vue")['default']
    'BlocksOfferComponent': typeof import("../components/Blocks/OfferComponent.vue")['default']
    'BlocksTabsPortfolioComponent': typeof import("../components/Blocks/TabsPortfolioComponent.vue")['default']
    'BlogCardComponent': typeof import("../components/Blog/BlogCardComponent.vue")['default']
    'BlogLightsArticleComponent': typeof import("../components/Blog/LightsArticleComponent.vue")['default']
    'FooterComponent': typeof import("../components/Footer/FooterComponent.vue")['default']
    'HeaderComponent': typeof import("../components/Header/HeaderComponent.vue")['default']
    'HeaderSmComponent': typeof import("../components/Header/HeaderSmComponent.vue")['default']
    'LoaderComponent': typeof import("../components/Loader/LoaderComponent.vue")['default']
    'ProjectsProjectCardComponent': typeof import("../components/Projects/ProjectCardComponent.vue")['default']
    'ProjectsSingleComponent': typeof import("../components/Projects/SingleComponent.vue")['default']
    'SwipersFullWidthImage': typeof import("../components/Swipers/FullWidthImage.vue")['default']
    'SwipersHomeGallery': typeof import("../components/Swipers/HomeGallery.vue")['default']
    'SwipersNewsSwiperComponent': typeof import("../components/Swipers/NewsSwiperComponent.vue")['default']
    'SwipersProjectsSwiperComponent': typeof import("../components/Swipers/ProjectsSwiperComponent.vue")['default']
    'SwipersReviewsSliderComponent': typeof import("../components/Swipers/ReviewsSliderComponent.vue")['default']
    'ToolsBreadcrumbs': typeof import("../components/Tools/Breadcrumbs.vue")['default']
    'ToolsCostCalculator': typeof import("../components/Tools/CostCalculator.vue")['default']
    'ToolsFaqComponent': typeof import("../components/Tools/FaqComponent.vue")['default']
    'ToolsGoogleReviewsComponent': typeof import("../components/Tools/GoogleReviewsComponent.vue")['default']
    'ToolsLangSwitchComponent': typeof import("../components/Tools/LangSwitchComponent.vue")['default']
    'ToolsPhoneInputComponent': typeof import("../components/Tools/PhoneInputComponent.vue")['default']
    'ToolsSearchComponent': typeof import("../components/Tools/SearchComponent.vue")['default']
    'ToolsSliderArrowsComponent': typeof import("../components/Tools/SliderArrowsComponent.vue")['default']
    'ToolsSocialMedias': typeof import("../components/Tools/SocialMedias.vue")['default']
    'ToolsTetsComp': typeof import("../components/Tools/TetsComp.vue")['default']
    'ToolsValuesArrowsComponent': typeof import("../components/Tools/ValuesArrowsComponent.vue")['default']
    'ToolsWhyWeComponent': typeof import("../components/Tools/WhyWeComponent.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBlocksContactShield': typeof import("../components/Blocks/ContactShield.vue")['default']
    'LazyBlocksContactShield2': typeof import("../components/Blocks/ContactShield2.vue")['default']
    'LazyBlocksContactShield3': typeof import("../components/Blocks/ContactShield3.vue")['default']
    'LazyBlocksHomeStatsComponent': typeof import("../components/Blocks/HomeStatsComponent.vue")['default']
    'LazyBlocksOfferComponent': typeof import("../components/Blocks/OfferComponent.vue")['default']
    'LazyBlocksTabsPortfolioComponent': typeof import("../components/Blocks/TabsPortfolioComponent.vue")['default']
    'LazyBlogCardComponent': typeof import("../components/Blog/BlogCardComponent.vue")['default']
    'LazyBlogLightsArticleComponent': typeof import("../components/Blog/LightsArticleComponent.vue")['default']
    'LazyFooterComponent': typeof import("../components/Footer/FooterComponent.vue")['default']
    'LazyHeaderComponent': typeof import("../components/Header/HeaderComponent.vue")['default']
    'LazyHeaderSmComponent': typeof import("../components/Header/HeaderSmComponent.vue")['default']
    'LazyLoaderComponent': typeof import("../components/Loader/LoaderComponent.vue")['default']
    'LazyProjectsProjectCardComponent': typeof import("../components/Projects/ProjectCardComponent.vue")['default']
    'LazyProjectsSingleComponent': typeof import("../components/Projects/SingleComponent.vue")['default']
    'LazySwipersFullWidthImage': typeof import("../components/Swipers/FullWidthImage.vue")['default']
    'LazySwipersHomeGallery': typeof import("../components/Swipers/HomeGallery.vue")['default']
    'LazySwipersNewsSwiperComponent': typeof import("../components/Swipers/NewsSwiperComponent.vue")['default']
    'LazySwipersProjectsSwiperComponent': typeof import("../components/Swipers/ProjectsSwiperComponent.vue")['default']
    'LazySwipersReviewsSliderComponent': typeof import("../components/Swipers/ReviewsSliderComponent.vue")['default']
    'LazyToolsBreadcrumbs': typeof import("../components/Tools/Breadcrumbs.vue")['default']
    'LazyToolsCostCalculator': typeof import("../components/Tools/CostCalculator.vue")['default']
    'LazyToolsFaqComponent': typeof import("../components/Tools/FaqComponent.vue")['default']
    'LazyToolsGoogleReviewsComponent': typeof import("../components/Tools/GoogleReviewsComponent.vue")['default']
    'LazyToolsLangSwitchComponent': typeof import("../components/Tools/LangSwitchComponent.vue")['default']
    'LazyToolsPhoneInputComponent': typeof import("../components/Tools/PhoneInputComponent.vue")['default']
    'LazyToolsSearchComponent': typeof import("../components/Tools/SearchComponent.vue")['default']
    'LazyToolsSliderArrowsComponent': typeof import("../components/Tools/SliderArrowsComponent.vue")['default']
    'LazyToolsSocialMedias': typeof import("../components/Tools/SocialMedias.vue")['default']
    'LazyToolsTetsComp': typeof import("../components/Tools/TetsComp.vue")['default']
    'LazyToolsValuesArrowsComponent': typeof import("../components/Tools/ValuesArrowsComponent.vue")['default']
    'LazyToolsWhyWeComponent': typeof import("../components/Tools/WhyWeComponent.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BlocksContactShield: typeof import("../components/Blocks/ContactShield.vue")['default']
export const BlocksContactShield2: typeof import("../components/Blocks/ContactShield2.vue")['default']
export const BlocksContactShield3: typeof import("../components/Blocks/ContactShield3.vue")['default']
export const BlocksHomeStatsComponent: typeof import("../components/Blocks/HomeStatsComponent.vue")['default']
export const BlocksOfferComponent: typeof import("../components/Blocks/OfferComponent.vue")['default']
export const BlocksTabsPortfolioComponent: typeof import("../components/Blocks/TabsPortfolioComponent.vue")['default']
export const BlogCardComponent: typeof import("../components/Blog/BlogCardComponent.vue")['default']
export const BlogLightsArticleComponent: typeof import("../components/Blog/LightsArticleComponent.vue")['default']
export const FooterComponent: typeof import("../components/Footer/FooterComponent.vue")['default']
export const HeaderComponent: typeof import("../components/Header/HeaderComponent.vue")['default']
export const HeaderSmComponent: typeof import("../components/Header/HeaderSmComponent.vue")['default']
export const LoaderComponent: typeof import("../components/Loader/LoaderComponent.vue")['default']
export const ProjectsProjectCardComponent: typeof import("../components/Projects/ProjectCardComponent.vue")['default']
export const ProjectsSingleComponent: typeof import("../components/Projects/SingleComponent.vue")['default']
export const SwipersFullWidthImage: typeof import("../components/Swipers/FullWidthImage.vue")['default']
export const SwipersHomeGallery: typeof import("../components/Swipers/HomeGallery.vue")['default']
export const SwipersNewsSwiperComponent: typeof import("../components/Swipers/NewsSwiperComponent.vue")['default']
export const SwipersProjectsSwiperComponent: typeof import("../components/Swipers/ProjectsSwiperComponent.vue")['default']
export const SwipersReviewsSliderComponent: typeof import("../components/Swipers/ReviewsSliderComponent.vue")['default']
export const ToolsBreadcrumbs: typeof import("../components/Tools/Breadcrumbs.vue")['default']
export const ToolsCostCalculator: typeof import("../components/Tools/CostCalculator.vue")['default']
export const ToolsFaqComponent: typeof import("../components/Tools/FaqComponent.vue")['default']
export const ToolsGoogleReviewsComponent: typeof import("../components/Tools/GoogleReviewsComponent.vue")['default']
export const ToolsLangSwitchComponent: typeof import("../components/Tools/LangSwitchComponent.vue")['default']
export const ToolsPhoneInputComponent: typeof import("../components/Tools/PhoneInputComponent.vue")['default']
export const ToolsSearchComponent: typeof import("../components/Tools/SearchComponent.vue")['default']
export const ToolsSliderArrowsComponent: typeof import("../components/Tools/SliderArrowsComponent.vue")['default']
export const ToolsSocialMedias: typeof import("../components/Tools/SocialMedias.vue")['default']
export const ToolsTetsComp: typeof import("../components/Tools/TetsComp.vue")['default']
export const ToolsValuesArrowsComponent: typeof import("../components/Tools/ValuesArrowsComponent.vue")['default']
export const ToolsWhyWeComponent: typeof import("../components/Tools/WhyWeComponent.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBlocksContactShield: typeof import("../components/Blocks/ContactShield.vue")['default']
export const LazyBlocksContactShield2: typeof import("../components/Blocks/ContactShield2.vue")['default']
export const LazyBlocksContactShield3: typeof import("../components/Blocks/ContactShield3.vue")['default']
export const LazyBlocksHomeStatsComponent: typeof import("../components/Blocks/HomeStatsComponent.vue")['default']
export const LazyBlocksOfferComponent: typeof import("../components/Blocks/OfferComponent.vue")['default']
export const LazyBlocksTabsPortfolioComponent: typeof import("../components/Blocks/TabsPortfolioComponent.vue")['default']
export const LazyBlogCardComponent: typeof import("../components/Blog/BlogCardComponent.vue")['default']
export const LazyBlogLightsArticleComponent: typeof import("../components/Blog/LightsArticleComponent.vue")['default']
export const LazyFooterComponent: typeof import("../components/Footer/FooterComponent.vue")['default']
export const LazyHeaderComponent: typeof import("../components/Header/HeaderComponent.vue")['default']
export const LazyHeaderSmComponent: typeof import("../components/Header/HeaderSmComponent.vue")['default']
export const LazyLoaderComponent: typeof import("../components/Loader/LoaderComponent.vue")['default']
export const LazyProjectsProjectCardComponent: typeof import("../components/Projects/ProjectCardComponent.vue")['default']
export const LazyProjectsSingleComponent: typeof import("../components/Projects/SingleComponent.vue")['default']
export const LazySwipersFullWidthImage: typeof import("../components/Swipers/FullWidthImage.vue")['default']
export const LazySwipersHomeGallery: typeof import("../components/Swipers/HomeGallery.vue")['default']
export const LazySwipersNewsSwiperComponent: typeof import("../components/Swipers/NewsSwiperComponent.vue")['default']
export const LazySwipersProjectsSwiperComponent: typeof import("../components/Swipers/ProjectsSwiperComponent.vue")['default']
export const LazySwipersReviewsSliderComponent: typeof import("../components/Swipers/ReviewsSliderComponent.vue")['default']
export const LazyToolsBreadcrumbs: typeof import("../components/Tools/Breadcrumbs.vue")['default']
export const LazyToolsCostCalculator: typeof import("../components/Tools/CostCalculator.vue")['default']
export const LazyToolsFaqComponent: typeof import("../components/Tools/FaqComponent.vue")['default']
export const LazyToolsGoogleReviewsComponent: typeof import("../components/Tools/GoogleReviewsComponent.vue")['default']
export const LazyToolsLangSwitchComponent: typeof import("../components/Tools/LangSwitchComponent.vue")['default']
export const LazyToolsPhoneInputComponent: typeof import("../components/Tools/PhoneInputComponent.vue")['default']
export const LazyToolsSearchComponent: typeof import("../components/Tools/SearchComponent.vue")['default']
export const LazyToolsSliderArrowsComponent: typeof import("../components/Tools/SliderArrowsComponent.vue")['default']
export const LazyToolsSocialMedias: typeof import("../components/Tools/SocialMedias.vue")['default']
export const LazyToolsTetsComp: typeof import("../components/Tools/TetsComp.vue")['default']
export const LazyToolsValuesArrowsComponent: typeof import("../components/Tools/ValuesArrowsComponent.vue")['default']
export const LazyToolsWhyWeComponent: typeof import("../components/Tools/WhyWeComponent.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
